QueryBuilderHelper: normalizeAndAddJoins quote
ERROR: missing FROM-clause entry for table "categorynodes"

SELECT COUNT(*) FROM "blog_post" AS "blog_post" LEFT JOIN blog_post_category AS "categoryNodes" ON ("blog_post"."id" = "categoryNodes"."post_id") WHERE categoryNodes.category_id = 3

needs to be quoted

WHERE "categoryNodes".category_id = 3